#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# STAGES: the #29 production console pass. One stage per thing a human does.
#
# Run from the repo root:   bash scripts/deploy-wizard.sh
# Writes captured values to .env.prod (gitignored: `.env*`), which is NOT a
# file Next.js loads — `.env.prod` is outside its `.env.{development,
# production}[.local]` set — so `pnpm build`/`pnpm dev` never pick up
# production keys by accident. Phase 4 (migration + ingest) reads it with
# `set -a; source .env.prod`. GitHub secrets are set for eval.yml,
# keepalive.yml and recrawl.yml. The decisions behind every value are in
# issue #29 (comments of 2026-09-12/14/15) and docs/runbook.md §7.
# ──────────────────────────────────────────────────────────────────────────

# Unconditional: the library above already defaulted ENV_FILE to ".env", which
# Next.js loads, so a `${ENV_FILE:-…}` here would never take effect.
ENV_FILE=".env.prod"
TOTAL_STAGES=12
SITE_URL="https://tramitico.com"
MAIL_DOMAIN="mail.tramitico.com"

# Resume: START_STAGE=9 bash scripts/deploy-wizard.sh skips straight to stage 9.
# Every stage's inputs come from ENV_FILE (written by the earlier stages), so a
# later stage never depends on an earlier one having run in this process.
# Dashboards' copy buttons can append invisible characters (the first run
# captured a service-role key ending in U+2028, which every HTTP client then
# rejected as a header value). Strip them from every captured value.
_strip_invisible() {
  local v="${!1}"
  v="${v//$'\u2028'/}"; v="${v//$'\u2029'/}"; v="${v//$'\u00a0'/}"; v="${v//$'\ufeff'/}"; v="${v//$'\r'/}"
  printf -v "$1" '%s' "$v"
}
eval "$(declare -f ask | sed '1s/^ask/_ask_raw/')"
eval "$(declare -f ask_secret | sed '1s/^ask_secret/_ask_secret_raw/')"
ask()        { _ask_raw "$@";        _strip_invisible "$1"; }
ask_secret() { _ask_secret_raw "$@"; _strip_invisible "$1"; }

START_STAGE="${START_STAGE:-1}"
_load_env() {
  [[ -f "$ENV_FILE" ]] || return 0
  local line key
  while IFS= read -r line; do
    [[ -z "$line" || "$line" == \#* || "$line" != *=* ]] && continue
    key="${line%%=*}"
    printf -v "$key" '%s' "${line#*=}"
  done < "$ENV_FILE"
}
_load_env
if [[ ! "$START_STAGE" =~ ^[0-9]+$ ]] ||
   (( 10#$START_STAGE < 1 || 10#$START_STAGE > TOTAL_STAGES )); then
  printf 'START_STAGE must be an integer from 1 to %s\n' "$TOTAL_STAGES" >&2
  exit 2
fi
START_STAGE=$((10#$START_STAGE))
_STAGE_INDEX=$((START_STAGE - 1))
SUPABASE_URL="${SUPABASE_URL:-}"
CALLBACK="${SUPABASE_URL}/auth/v1/callback"
SMTP_ADMIN_EMAIL="${SMTP_ADMIN_EMAIL:-no-reply@${MAIL_DOMAIN}}"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage_1() {
stage "Supabase: the production project"
say "One free project; production, eval.yml, keepalive.yml and recrawl.yml all use it."
open_url "https://supabase.com/dashboard/new"
step "Name: tramitico · Region: East US (North Virginia), us-east-1 — same place as Vercel's iad1."
step "Generate a database password and keep it: the CLI needs it to link."
ask_secret SUPABASE_DB_PASSWORD "Paste the database password:"
step "Wait for the project to finish provisioning (a minute or two)."
step "Project Settings → General → copy the Project ID (the 20-char ref)."
ask SUPABASE_PROJECT_REF "Paste the project ref:"
SUPABASE_URL="https://${SUPABASE_PROJECT_REF}.supabase.co"
CALLBACK="${SUPABASE_URL}/auth/v1/callback"
say "Project URL: ${SUPABASE_URL}"
write_env SUPABASE_DB_PASSWORD "$SUPABASE_DB_PASSWORD"
write_env SUPABASE_PROJECT_REF "$SUPABASE_PROJECT_REF"
write_env SUPABASE_URL "$SUPABASE_URL"
write_env NEXT_PUBLIC_SUPABASE_URL "$SUPABASE_URL"
pause
}

# ── 2 ─────────────────────────────────────────────────────────────────────
stage_2() {
stage "Supabase: API keys and the JWT signing mode"
open_url "https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF}/settings/api-keys"
step "Publishable key (sb_publishable_…): what the browser and server clients use."
ask NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY "Paste the publishable key:"
step "Secret key: create one named 'tramitico-app' (or reveal the legacy service_role)."
ask_secret SUPABASE_SERVICE_ROLE_KEY "Paste the secret / service_role key:"
step "Legacy tab → anon key. Only retrieval.eval.test.ts's grants suite reads it (eval.yml)."
ask_secret SUPABASE_ANON_KEY "Paste the legacy anon key:"
write_env NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY "$NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY"
write_env SUPABASE_SERVICE_ROLE_KEY "$SUPABASE_SERVICE_ROLE_KEY"
write_env SUPABASE_ANON_KEY "$SUPABASE_ANON_KEY"
say ""
say "Signing-key mode (#124 carry-over): decides what getClaims() trusts — see CONTEXT.md."
open_url "https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF}/settings/jwt"
step "Read which key is CURRENT: ECC (ES256) / RSA (RS256) = asymmetric; Legacy HS256 = symmetric."
ask JWT_SIGNING_MODE "Type the algorithm as shown (ES256 / RS256 / HS256):"
write_env JWT_SIGNING_MODE "$JWT_SIGNING_MODE"
note "Claude turns this into the CONTEXT.md note in Phase 7."
pause
}

# ── 3 ─────────────────────────────────────────────────────────────────────
stage_3() {
stage "Anthropic: the tramitico-prod workspace and its cap"
say "Production gets its own workspace, key and a US\$10/month limit (runbook §7)."
open_url "https://console.anthropic.com/settings/workspaces"
step "Create workspace 'tramitico-prod'."
step "Open it → Limits → Monthly spend limit: 10 USD."
step "API Keys → Create key in that workspace, name 'vercel-prod'."
ask_secret ANTHROPIC_API_KEY "Paste the tramitico-prod key (for Vercel only):"
write_env ANTHROPIC_API_KEY "$ANTHROPIC_API_KEY"
warn "This key goes to Vercel and nowhere else. eval.yml uses the EVAL workspace's key (stage 9)."
pause
}

# ── 4 ─────────────────────────────────────────────────────────────────────
stage_4() {
stage "Voyage AI: a production key, and the rate tier"
say "Voyage bills per account, not per key: a second key is for revocability."
open_url "https://dashboard.voyageai.com/api-keys"
step "Create key 'tramitico-prod'."
ask_secret VOYAGE_API_KEY "Paste the Voyage prod key:"
write_env VOYAGE_API_KEY "$VOYAGE_API_KEY"
say ""
warn "Tier check (ADR 0003): without a payment method Voyage allows ~3 requests/min."
say "Production makes one embedding call per ask; 3/min is an outage under any traffic."
open_url "https://dashboard.voyageai.com/billing"
step "Confirm a payment method is on file. The 200M free tokens still apply; a full ingest is < 1M."
if ! confirm "Is a payment method on file (standard rate limits)?"; then
  SKIPPED+=("Voyage: add a payment method so production is not on the 3 req/min tier")
fi
pause
}

# ── 5 ─────────────────────────────────────────────────────────────────────
stage_5() {
stage "Resend: sending domain ${MAIL_DOMAIN}"
say "Auth email for magic links. The subdomain keeps SPF/DKIM off the apex (runbook §7)."
open_url "https://resend.com/domains"
step "Add domain: ${MAIL_DOMAIN} · Region: North Virginia (us-east-1)."
step "Resend shows the DNS records: one DKIM TXT/CNAME, one SPF TXT, and an MX for bounces."
say "Add them at Vercel DNS, exactly as shown:"
open_url "https://vercel.com/dashboard"
step "Dashboard → left sidebar Domains → tramitico.com → DNS Records (the form at the bottom)."
step "tramitico.com → DNS Records → add each record (name relative to the apex, e.g. 'resend._domainkey.mail')."
pause "Records added at Vercel? (Enter)"
step "Back in Resend, click Verify. Propagation is usually minutes."
pause "Domain shows Verified? (Enter)"
open_url "https://resend.com/api-keys"
step "Create API key 'supabase-smtp', permission Sending access, domain ${MAIL_DOMAIN}."
say "Supabase SMTP uses it as the password (user is literally 'resend')."
ask_secret SMTP_PASS "Paste the Resend API key:"
ask SMTP_ADMIN_EMAIL "Admin/sender address [no-reply@${MAIL_DOMAIN}]:"
SMTP_ADMIN_EMAIL="${SMTP_ADMIN_EMAIL:-no-reply@${MAIL_DOMAIN}}"
write_env SMTP_PASS "$SMTP_PASS"
write_env SMTP_ADMIN_EMAIL "$SMTP_ADMIN_EMAIL"
pause
}

# ── 6 ─────────────────────────────────────────────────────────────────────
stage_6() {
stage "ImprovMX: privacidad@tramitico.com"
say "/privacidad names this mailbox; it must reach you before launch (#136)."
open_url "https://improvmx.com/"
step "Add domain tramitico.com · alias 'privacidad' → your inbox."
step "ImprovMX shows two MX records and one SPF TXT for the APEX (not mail.)."
open_url "https://vercel.com/dashboard"
step "Dashboard → left sidebar Domains → tramitico.com → DNS Records (the form at the bottom)."
step "Add them on tramitico.com. If an apex SPF TXT already exists, merge: 'v=spf1 include:spf.improvmx.com ~all'."
pause "Records added and ImprovMX shows the domain as active? (Enter)"
step "Send a test mail to privacidad@tramitico.com from any account and confirm it arrives."
if ! confirm "Did the test mail arrive?"; then
  SKIPPED+=("privacidad@tramitico.com forwarding — re-test after DNS propagates")
fi
}

# ── 7 ─────────────────────────────────────────────────────────────────────
stage_7() {
stage "GitHub OAuth app"
open_url "https://github.com/settings/applications/new"
step "Name: Tramitico · Homepage: ${SITE_URL}"
step "Authorization callback URL: ${CALLBACK}"
step "Register, then Generate a new client secret."
ask GITHUB_OAUTH_CLIENT_ID "Paste the Client ID:"
ask_secret GITHUB_OAUTH_CLIENT_SECRET "Paste the client secret:"
write_env GITHUB_OAUTH_CLIENT_ID "$GITHUB_OAUTH_CLIENT_ID"
write_env GITHUB_OAUTH_CLIENT_SECRET "$GITHUB_OAUTH_CLIENT_SECRET"
pause
}

# ── 8 ─────────────────────────────────────────────────────────────────────
stage_8() {
stage "Google OAuth client"
say "Basic scopes only (#84): no Google verification review, but the consent screen must be Published."
open_url "https://console.cloud.google.com/apis/credentials"
step "Pick/create a project 'tramitico'. First: OAuth consent screen (Branding)."
step "  App name Tramitico · support email yours · Homepage ${SITE_URL}"
step "  Privacy policy ${SITE_URL}/privacidad · Terms ${SITE_URL}/terminos"
step "  Audience: External → Publish app (Testing would only let listed test users sign in)."
step "Then Credentials → Create credentials → OAuth client ID → Web application."
step "  Authorized JavaScript origin: ${SITE_URL}"
step "  Authorized redirect URI: ${CALLBACK}"
ask GOOGLE_OAUTH_CLIENT_ID "Paste the Client ID:"
ask_secret GOOGLE_OAUTH_CLIENT_SECRET "Paste the client secret:"
write_env GOOGLE_OAUTH_CLIENT_ID "$GOOGLE_OAUTH_CLIENT_ID"
write_env GOOGLE_OAUTH_CLIENT_SECRET "$GOOGLE_OAUTH_CLIENT_SECRET"
pause
}

# ── 9 ─────────────────────────────────────────────────────────────────────
stage_9() {
stage "Supabase Auth: configure the hosted project (dashboard only)"
warn "Never 'supabase config push': it would upload the localhost site_url (supabase/config.toml)."
open_url "https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF}/auth/url-configuration"
step "Site URL: ${SITE_URL}"
step "Redirect URLs: exactly one — ${SITE_URL}/auth/callback   (prod only, no previews)"
pause "Saved? (Enter)"
open_url "https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF}/auth/smtp"
step "Emails → SMTP Settings → Enable custom SMTP:"
step "  Sender email ${SMTP_ADMIN_EMAIL} · Sender name Tramitico"
step "  Host smtp.resend.com · Port 465 · Username resend · Password = the Resend API key"
step "Then sidebar → Rate Limits → emails sent per hour: 10 (Resend free is 100/day)."
pause "Saved? (Enter)"
open_url "https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF}/auth/providers"
step "User Signups block (top of page): Confirm email OFF — matches config.toml's enable_confirmations=false."
note "ON sends Supabase's Confirm-signup template to new addresses; its link bypasses /auth/confirm and nobody gets a session."
step "Email provider panel: Email OTP length 6 (hosted default is 8; the sign-in form accepts exactly six)."
step "GitHub: enable · Client ID ${GITHUB_OAUTH_CLIENT_ID} · secret from stage 7."
step "Google: enable · Client ID ${GOOGLE_OAUTH_CLIENT_ID} · secret from stage 8."
pause "All three providers saved? (Enter)"
open_url "https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF}/auth/templates"
step "Magic Link template: mirror supabase/config.toml's [auth.email.template.magic_link] —"
step "  the link must land on ${SITE_URL}/auth/confirm with the token hash (see supabase/templates/)."
pause "Template saved? (Enter)"
}

# ── 10 ────────────────────────────────────────────────────────────────────
stage_10() {
stage "GitHub Actions: secrets and variables for eval.yml / keepalive.yml / recrawl.yml"
say "These workflows read production directly (runbook §7). Names must match exactly."
set_secret SUPABASE_URL "$SUPABASE_URL"
set_secret SUPABASE_SERVICE_ROLE_KEY "$SUPABASE_SERVICE_ROLE_KEY"
set_secret SUPABASE_ANON_KEY "$SUPABASE_ANON_KEY"
set_secret VOYAGE_API_KEY "$VOYAGE_API_KEY"
say ""
say "eval.yml's ANTHROPIC_API_KEY is the EVAL workspace key, not tramitico-prod's:"
say "an authorized run must never be blocked by, or spend, production's US\$10 cap."
ask_secret ANTHROPIC_EVAL_API_KEY "Paste the eval-workspace Anthropic key:"
set_secret ANTHROPIC_API_KEY "$ANTHROPIC_EVAL_API_KEY"
set_var EMBEDDINGS_PROVIDER "voyage"
note "RERANK / EXPAND / ANSWER_MODEL / EXPAND_MODEL variables stay unset: empty is the shipped default."
pause
}

# ── 11 ────────────────────────────────────────────────────────────────────
stage_11() {
stage "Database: link, migrate, ingest (Phase 4)"
say "Needs the Supabase CLI, Voyage key and ~5 minutes. Idempotent; safe to re-run."
say "Skip this stage to hand it to Claude — the same commands, reading ${ENV_FILE}."
if confirm "Run migration + ingest against production now?"; then
  export SUPABASE_DB_PASSWORD
  supabase link --project-ref "$SUPABASE_PROJECT_REF"
  supabase db push
  EMBEDDINGS_PROVIDER=voyage VOYAGE_API_KEY="$VOYAGE_API_KEY" \
    SUPABASE_URL="$SUPABASE_URL" SUPABASE_SERVICE_ROLE_KEY="$SUPABASE_SERVICE_ROLE_KEY" \
    pnpm ingest
  if git diff --quiet -- eval/corpus-index.json; then
    say "✓ eval/corpus-index.json unchanged: production holds the corpus CI was tested against (#163)."
  else
    warn "eval/corpus-index.json CHANGED — production differs from the committed corpus. Do not commit blindly; investigate."
    SKIPPED+=("Ingest produced a different eval/corpus-index.json: reconcile before launch")
  fi
else
  SKIPPED+=("Phase 4: supabase link/db push + pnpm ingest against production (Claude, from ${ENV_FILE})")
fi
pause
}

# ── 12 ────────────────────────────────────────────────────────────────────
stage_12() {
stage "Vercel: project, env, domain, preview protection"
RATE_LIMIT_SUBJECT_SECRET=$(_existing RATE_LIMIT_SUBJECT_SECRET || openssl rand -hex 32)
write_env RATE_LIMIT_SUBJECT_SECRET "$RATE_LIMIT_SUBJECT_SECRET"
write_env NEXT_PUBLIC_SITE_URL "$SITE_URL"
write_env EMBEDDINGS_PROVIDER "voyage"
write_env RERANK "on"
write_env RATE_LIMIT_ANON "10"
write_env RATE_LIMIT_AUTHED "10"
open_url "https://vercel.com/new"
step "Import rjwrld/tramitico · Framework Next.js · Hobby · Production branch main."
step "Environment Variables (Production only — previews carry no keys). Copy each from ${ENV_FILE}:"
for k in NEXT_PUBLIC_SUPABASE_URL NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY SUPABASE_URL \
         SUPABASE_SERVICE_ROLE_KEY EMBEDDINGS_PROVIDER VOYAGE_API_KEY ANTHROPIC_API_KEY \
         RERANK RATE_LIMIT_ANON RATE_LIMIT_AUTHED RATE_LIMIT_SUBJECT_SECRET NEXT_PUBLIC_SITE_URL; do
  say "    $k"
done
note "Not set (empty = shipped default): ANSWER_MODEL CONDENSE_MODEL EXPAND EXPAND_MODEL."
step "Deploy."
pause "First deploy finished? (Enter)"
step "Project → Settings → Domains: add tramitico.com (primary) and www.tramitico.com → redirect to apex."
step "Project → Settings → Deployment Protection → Vercel Authentication: ON for Preview (free on Hobby)."
step "Project → Settings → Functions → region: Washington D.C. (iad1) — same as Supabase us-east-1."
pause "Domain live and protection on? (Enter)"
say ""
say "Now Phase 7 with Claude: runbook §5 (five steps), HSTS curl, one sign-in per provider,"
say "SPF/DKIM 'pass' on a real magic link, results as a comment on #29, CONTEXT.md signing-key PR."
}

banner "Tramitico → production (#29)"
for n in $(seq "$START_STAGE" "$TOTAL_STAGES"); do "stage_$n"; done
finish
