#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


# ──────────────────────────────────────────────────────────────────────────
# STAGES: the #252 visibility flip. One stage per repository setting.
#
# Run from the repo root, on `main`:   bash scripts/public-release-wizard.sh
#
# Unlike deploy-wizard.sh this captures no values: every stage is a `gh`
# call the owner runs from their own shell (the agent's permission classifier
# blocks repo-settings writes, the owner's does not), followed by a read-back
# that proves the setting took. The evidence behind each step — what was
# scanned and what it found — is docs/audits/2026-09-17-public-release-review.md.
# The order matters: stages 2–4 work on a private repository, stages 6–8 are
# features GitHub only offers a public one on the free plan, so they follow
# the flip in stage 5. START_STAGE=N resumes at stage N — after stage 1, which
# always runs, so no resume skips the fetch and the secret scan.
# ──────────────────────────────────────────────────────────────────────────

ENV_FILE=".env.release" # never written; keeps the library's `ask` defaults inert
TOTAL_STAGES=11
REPO="rjwrld/tramitico"
SITE_URL="https://tramitico.com"
REVIEW_DOC="docs/audits/2026-09-17-public-release-review.md"
TAG="v0.1.0"
TOPICS="rag,retrieval-augmented-generation,nextjs,react,typescript,supabase,pgvector,postgresql,claude,anthropic,costa-rica,impuestos,hacienda,ccss,llm-evaluation"
PROTECTION_CONTEXTS='["checks","suites","e2e"]'

START_STAGE="${START_STAGE:-1}"
if [[ ! "$START_STAGE" =~ ^[0-9]+$ ]] ||
   (( 10#$START_STAGE < 1 || 10#$START_STAGE > TOTAL_STAGES )); then
  printf 'START_STAGE must be an integer from 1 to %s\n' "$TOTAL_STAGES" >&2
  exit 2
fi
START_STAGE=$((10#$START_STAGE))

# show LABEL VALUE prints one read-back line: what the API says now.
show() { printf '  %s%-28s%s %s\n' "$DIM" "$1" "$RESET" "$2"; }

# run_gh "what" cmd args... echoes the command, runs it, and records a skip
# instead of aborting when it fails, so a later stage can still run.
run_gh() {
  local what="$1"; shift
  printf '  %s$%s %s\n' "$DIM" "$RESET" "$*"
  if "$@"; then
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$what"
  else
    SKIPPED+=("$what")
    warn "failed: $what — fix it and re-run with START_STAGE=$_STAGE_INDEX"
    return 1
  fi
}

# api_get PATH JQ reads one repository fact, or prints "—" when the endpoint
# answers 404 (which is how GitHub says "off" for several of these).
api_get() {
  local out
  if out=$(gh api "repos/${REPO}$1" --jq "$2" 2>/dev/null) && [[ -n "$out" ]]; then
    printf '%s' "$out"
  else
    printf '—'
  fi
}

visibility()      { api_get "" ".visibility"; }
secret_scanning() { api_get "" '.security_and_analysis.secret_scanning.status // "off"'; }
push_protection() { api_get "" '.security_and_analysis.secret_scanning_push_protection.status // "off"'; }
dependabot_alerts() { gh api "repos/${REPO}/vulnerability-alerts" >/dev/null 2>&1 && printf 'enabled' || printf 'disabled'; }
security_fixes()  { api_get "/automated-security-fixes" ".enabled"; }
pvr()             { api_get "/private-vulnerability-reporting" ".enabled"; }
protection()      { api_get "/branches/main/protection" '.required_status_checks.contexts | join(",")'; }
license_id()      { api_get "" ".license.spdx_id"; }

# ── 1 ─────────────────────────────────────────────────────────────────────
stage_1() {
stage "Pre-flight: the tree, the scan, the review"
say "This flips ${REPO} public. Everything below is reversible except the flip itself:"
say "once public, the history, issues and Actions logs have been seen."
say ""
local branch; branch=$(git rev-parse --abbrev-ref HEAD)
show "branch" "$branch"
show "working tree" "$(git status --porcelain | wc -l | tr -d ' ') uncommitted path(s)"
# Every branch and tag on the remote becomes public, so every one of them is
# fetched before the scan: gitleaks only sees refs that exist locally.
if ! git fetch -q --prune origin \
  '+refs/heads/*:refs/remotes/origin/*' \
  '+refs/tags/*:refs/tags/*'; then
  warn "could not fetch every branch and tag from origin; stopping."
  exit 1
fi
show "refs fetched" "$(git for-each-ref --format='%(refname)' refs/remotes/origin refs/tags | wc -l | tr -d ' ') (branches + tags)"
show "main vs origin/main" "$(git rev-list --left-right --count main...origin/main | awk '{print "ahead "$1", behind "$2}')"
show "last CI on main" "$(gh run list -R "$REPO" --branch main --workflow CI --limit 1 --json conclusion,headSha --jq '.[0] | "\(.conclusion) @ \(.headSha[0:7])"')"
say ""
if ! command -v gitleaks >/dev/null 2>&1; then
  warn "gitleaks is not installed (brew install gitleaks). The scan is the gate; stopping."
  exit 1
fi
step "Full-history secret scan (every branch and tag, .gitleaks.toml allowlist):"
if gitleaks git --log-opts=--all --no-banner . >/dev/null 2>&1; then
  printf '  %s✓%s gitleaks: no leaks found\n' "$GREEN" "$RESET"
else
  warn "gitleaks reported findings or failed to run. Read them before anything goes public:"
  say "    gitleaks git --log-opts=--all ."
  exit 1
fi
say ""
step "Read ${REVIEW_DOC}: it says what was scanned, what was found, and what this wizard changes."
if ! confirm "On main, clean, up to date, CI green, review read — continue?"; then
  say "Stopping. Re-run when the tree is ready."; exit 0
fi
}

# ── 2 ─────────────────────────────────────────────────────────────────────
stage_2() {
stage "Repository metadata: homepage, description, topics"
say "Works while private. The homepage still points at the vercel.app preview."
show "homepage (now)" "$(api_get "" ".homepage")"
show "description (now)" "$(api_get "" ".description")"
show "topics (now)" "$(api_get "" '.topics | join(",")')"
say ""
step "Homepage → ${SITE_URL}; topics → ${TOPICS//,/ }"
if confirm "Apply?"; then
  run_gh "homepage + topics" gh repo edit "$REPO" --homepage "$SITE_URL" --add-topic "$TOPICS" || true
  show "homepage" "$(api_get "" ".homepage")"
  show "topics" "$(api_get "" '.topics | join(",")')"
fi
pause
}

# ── 3 ─────────────────────────────────────────────────────────────────────
stage_3() {
stage "Dependabot: alerts and security updates"
say "Works while private. Version bumps are already scheduled by .github/dependabot.yml;"
say "these two switches add the advisory alerts and the PRs that fix them."
show "alerts (now)" "$(dependabot_alerts)"
show "security updates (now)" "$(security_fixes)"
say ""
if confirm "Enable both?"; then
  run_gh "Dependabot alerts" gh api -X PUT "repos/${REPO}/vulnerability-alerts" --silent || exit 1
  run_gh "Dependabot security updates" gh api -X PUT "repos/${REPO}/automated-security-fixes" --silent || exit 1
  show "alerts" "$(dependabot_alerts)"
  show "security updates" "$(security_fixes)"
fi
pause
}

# ── 4 ─────────────────────────────────────────────────────────────────────
stage_4() {
stage "Social preview image"
say "No API for this one. The card is docs/assets/social-preview.png (1280×640),"
say "rendered by scripts/generate-social-preview.ts from DESIGN §4's tokens."
open_url "https://github.com/${REPO}/settings"
step "Scroll to 'Social preview' → Edit → Upload an image… → pick docs/assets/social-preview.png."
step "Save. GitHub shows the crop; the card is already the right ratio."
pause "Uploaded? (Enter)"
}

# ── 5 ─────────────────────────────────────────────────────────────────────
stage_5() {
stage "The flip: private → public"
show "visibility (now)" "$(visibility)"
say ""
warn "Irreversible in practice. After this:"
say "  - every commit on every branch and tag is public (scanned 2026-09-17: clean)"
say "  - every Actions run log and artifact is public (scanned 2026-09-17: clean)"
say "  - issues, PRs and their comments are public"
say "  - stars and forks start from zero; nothing else about the repo changes"
say ""
if confirm "Make ${REPO} public now?"; then
  # Stages 6–8 only make sense on a public repository, and stages 10–11 would
  # tag and sign off a flip that never happened, so this one is a hard gate.
  if ! run_gh "visibility → public" gh repo edit "$REPO" --visibility public --accept-visibility-change-consequences; then
    warn "the visibility change failed; stopping before the public-only stages."
    exit 1
  fi
  local now; now=$(visibility)
  show "visibility" "$now"
  if [[ "$now" != "public" ]]; then
    warn "the API still reports '${now}'; stopping before the public-only stages."
    exit 1
  fi
else
  say "Not flipped. Stages 6–8 need a public repository; stopping here."
  finish; exit 0
fi
pause
}

# ── 6 ─────────────────────────────────────────────────────────────────────
stage_6() {
stage "Secret scanning and push protection"
say "Free on a public repository. Scanning finds a credential after the fact;"
say "push protection refuses the push that carries one."
show "secret scanning (now)" "$(secret_scanning)"
show "push protection (now)" "$(push_protection)"
say ""
if confirm "Enable both?"; then
  run_gh "secret scanning + push protection" gh api -X PATCH "repos/${REPO}" --silent --input - <<'JSON' || exit 1
{"security_and_analysis":{"secret_scanning":{"status":"enabled"},"secret_scanning_push_protection":{"status":"enabled"}}}
JSON
  show "secret scanning" "$(secret_scanning)"
  show "push protection" "$(push_protection)"
fi
pause
}

# ── 7 ─────────────────────────────────────────────────────────────────────
stage_7() {
stage "Private vulnerability reporting"
say "SECURITY.md names 'Security → Report a vulnerability' as the preferred path."
say "This is the switch that makes that button exist."
show "PVR (now)" "$(pvr)"
say ""
if confirm "Enable?"; then
  run_gh "private vulnerability reporting" gh api -X PUT "repos/${REPO}/private-vulnerability-reporting" --silent || exit 1
  show "PVR" "$(pvr)"
fi
pause
}

# ── 8 ─────────────────────────────────────────────────────────────────────
stage_8() {
stage "Branch protection on main"
say "Deferred on 2026-09-10 until public (paid while private); #316 merged with"
say "a red 'suites' check because nothing blocked the button. The decision:"
say "  - required contexts: checks, suites, e2e (the CI workflow's three jobs)"
say "  - enforce_admins: true — you are the only admin; without it this changes nothing"
say "  - no required reviews — a solo owner cannot self-approve"
say "  - strict: false — no 'branch must be up to date' churn"
say "  - CodeRabbit NOT required: it reports on PRs only, and a bot outage must not block main"
show "protection (now)" "$(protection)"
say ""
if confirm "Apply?"; then
  run_gh "branch protection on main" gh api -X PUT "repos/${REPO}/branches/main/protection" --silent --input - <<JSON || exit 1
{
  "required_status_checks": { "strict": false, "contexts": ${PROTECTION_CONTEXTS} },
  "enforce_admins": true,
  "required_pull_request_reviews": null,
  "restrictions": null,
  "allow_force_pushes": false,
  "allow_deletions": false,
  "required_conversation_resolution": false
}
JSON
  show "required contexts" "$(protection)"
  show "enforce_admins" "$(api_get "/branches/main/protection" ".enforce_admins.enabled")"
fi
pause
}

# ── 9 ─────────────────────────────────────────────────────────────────────
stage_9() {
stage "What the public sees"
show "license (API)" "$(license_id)"
show "security policy" "$(api_get "/community/profile" ".files.security.url // \"—\"")"
open_url "https://github.com/${REPO}"
step "The README renders: demo clips play, the numbers table and the License section are there."
open_url "https://github.com/${REPO}/security/policy"
step "The policy page shows SECURITY.md, and 'Report a vulnerability' is offered."
open_url "${SITE_URL}"
step "The live site answers; the footer's /privacidad and /terminos links work."
pause "All three look right? (Enter)"
}

# ── 10 ────────────────────────────────────────────────────────────────────
stage_10() {
stage "Tag ${TAG} and the first release"
# A resumed run (START_STAGE=10) never passed stage 5's gate, so read it again:
# the first *public* release cannot go on a private repository.
local now; now=$(visibility)
if [[ "$now" != "public" ]]; then
  warn "the repository is '${now}', not public; stopping before the release."
  exit 1
fi
say "The tag goes on the commit main is at now; the release notes point at the README"
say "rather than listing 350 pull requests."
git fetch -q origin main
local sha; sha=$(git rev-parse origin/main)
show "origin/main" "${sha:0:7} $(git log -1 --format=%s "$sha" | cut -c1-70)"
show "existing tag" "$(git ls-remote --tags origin "refs/tags/${TAG}" | cut -c1-7 | sed 's/^$/none/')"
say ""
if confirm "Tag ${sha:0:7} as ${TAG} and publish the release?"; then
  local notes; notes=$(mktemp)
  cat > "$notes" <<NOTES
First public release of Tramitico — a RAG assistant that answers the tax and
social-security questions of people who work for themselves in Costa Rica, with
every material claim cited to the official Hacienda, CCSS, SINALEVI or BCCR text.

- Live at ${SITE_URL}
- What it does, how it answers, and the measured numbers: the [README](https://github.com/${REPO}#readme)
- Every eval run and how to read one: [eval/README.md](https://github.com/${REPO}/blob/${TAG}/eval/README.md)
- License: Apache-2.0 for the code. The Tramitico name and mark, and the official
  documents in the corpus, are not covered — see the README's License section.

Tramitico is not legal or tax advice. Official sources change; the answer cites the
version it read.
NOTES
  # Fail-fast on purpose: without a pushed tag, `gh release create` would mint
  # one from the default branch's tip, which may not be $sha. `--verify-tag`
  # makes it refuse instead.
  if ! run_gh "tag ${TAG}" git tag -a "$TAG" "$sha" -m "Tramitico ${TAG} — first public release"; then
    rm -f "$notes"; return 1
  fi
  if ! run_gh "push tag" git push origin "refs/tags/${TAG}"; then
    rm -f "$notes"; return 1
  fi
  if ! run_gh "GitHub release" gh release create "$TAG" -R "$REPO" \
    --title "Tramitico ${TAG}" --notes-file "$notes" --latest --verify-tag; then
    rm -f "$notes"; return 1
  fi
  rm -f "$notes"
  show "release" "$(gh release view "$TAG" -R "$REPO" --json url --jq .url 2>/dev/null || printf '—')"
fi
pause
}

# ── 11 ────────────────────────────────────────────────────────────────────
stage_11() {
stage "The record on #252"
say "The visibility-change checklist wants who reviewed what. The agent's half is in"
say "${REVIEW_DOC}; this stage adds the owner's half: the settings as the API reads them now."
local body; body=$(mktemp)
cat > "$body" <<RECORD
## Visibility flip — $(date +%Y-%m-%d)

Run by $(gh api user --jq .login) via \`scripts/public-release-wizard.sh\`. Agent-side review: \`${REVIEW_DOC}\`.

| Setting | State (API read-back) |
| --- | --- |
| visibility | $(visibility) |
| license | $(license_id) |
| secret scanning | $(secret_scanning) |
| push protection | $(push_protection) |
| private vulnerability reporting | $(pvr) |
| Dependabot alerts | $(dependabot_alerts) |
| Dependabot security updates | $(security_fixes) |
| branch protection on main | contexts: $(protection); enforce_admins: $(api_get "/branches/main/protection" ".enforce_admins.enabled") |
| homepage | $(api_get "" ".homepage") |
| topics | $(api_get "" '.topics | join(", ")') |
| release | $(gh release view "$TAG" -R "$REPO" --json url --jq .url 2>/dev/null || printf 'not created') |

Reviewed by the owner in this run: the public README and demo, the security policy page, the live site. Social preview uploaded by hand.
RECORD
say ""
cat "$body" | sed 's/^/  /'
say ""
if confirm "Post this comment on #252?"; then
  run_gh "comment on #252" gh issue comment 252 -R "$REPO" --body-file "$body" || true
  if confirm "Close #252?"; then
    run_gh "close #252" gh issue close 252 -R "$REPO" --comment "Public since $(date +%Y-%m-%d); the record is the comment above." || true
  fi
fi
rm -f "$body"
}

banner "Tramitico → public: the #252 visibility flip"
# Pre-flight runs on every invocation, resumed or not: START_STAGE=5 must not
# be a way to flip the repository without this run's fetch and secret scan.
stage_1
FIRST_STAGE=$(( START_STAGE < 2 ? 2 : START_STAGE ))
_STAGE_INDEX=$((FIRST_STAGE - 1))
for n in $(seq "$FIRST_STAGE" "$TOTAL_STAGES"); do "stage_$n"; done
finish
